name: CD - Push NuGet package

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.101
      - name: Restore packages
        run: dotnet restore
      - name: Build Release
        run: dotnet build ShapeCrawler/ShapeCrawler.csproj --configuration Release --no-restore
      - name: Run tests
        run: dotnet test --configuration Release --no-restore --verbosity normal -f net7.0
      - name: Create NuGet package
        run: dotnet pack --configuration Release
      - name: Push NuGet package
        run: |
          dotnet nuget push -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json "ShapeCrawler\bin\Release\*.nupkg"
