name: Test

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.101
      
      - name: Restore packages
        run: dotnet restore
      
      - name: Build
        run: dotnet build ShapeCrawler/ShapeCrawler.csproj --configuration Release --no-restore
      
      - name: Test
        run: dotnet test --no-restore --verbosity normal -f net7.0