name: Pull Request

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # Windows runs both framework versions
          - os: windows-latest
            framework_version: 'net9.0'
          - os: windows-latest
            framework_version: 'net48'
          # Linux and macOS only run net9.0
          - os: ubuntu-latest
            framework_version: 'net9.0'
          - os: macos-14
            framework_version: 'net9.0'
      fail-fast: false    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x      
      - name: Run tests
        run: |
          dotnet test tests/ShapeCrawler.DevTests/ShapeCrawler.DevTests.csproj -c Release -f ${{ matrix.framework_version }}
          dotnet test tests/ShapeCrawler.CITests/ShapeCrawler.CITests.csproj -c Release -f ${{ matrix.framework_version }}