name: Test

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test on .NET 7.0
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3      
      
      - name: Restore packages
        run: dotnet restore    
      
      - name: Test
        run: dotnet test -c Release -f net7.0 --no-restore --verbosity normal