name: Pull Request

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest ]
        framework_version: [ 'net9.0', 'net48' ]
        exclude:
          - os: ubuntu-latest
            framework_version: 'net48'
      fail-fast: false    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x     
      
      - name: Test
        run: dotnet test -c Release -f ${{ matrix.framework_version }}