name: Publish package

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  
  test:
    name: Test on .NET Framework ${{ matrix.framework_version }}
    runs-on: windows-latest
    strategy:
      matrix:
        framework_version: [ 'net472', 'net48' ]
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: dotnet test -c Release -f ${{ matrix.framework_version }}

  publish-package:
    needs: test
    name: Publish package
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test on .NET 8
        run: dotnet test -c Release -f net8.0 --verbosity normal
      - name: Create the package
        run: dotnet pack --configuration Release /p:Version=${{ vars.VERSION }}
      - name: Publish the package to nuget.org
        run: dotnet nuget push -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json "src\ShapeCrawler\bin\Release\*.nupkg"