name: Push NuGet package

on:
  push:
    tags:
      - 'v*'    
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:  
  test-net48:
    name: Test on .NET Framework 4.8
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3    
      # - name: Setup .NET Framework 4.8
      #   run: |
      #     choco install netfx-4.8 -y      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1      
      - name: Setup VSTest
        uses: darenm/Setup-VSTest@v1.2      
      - name: Restore packages
        run: nuget restore      
      - name: Build
        run: msbuild /p:Configuration=Release      
      - name: Run tests
        run: vstest.console.exe **/*.*Tests.dll /Framework:Framework45
  
  push-package:
    name: Push NuGet package
    runs-on: windows-latest
    needs: [test-net48]
    if: needs.test-net48.result == 'success'
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      # - name: Setup .NET SDK
      #   uses: actions/setup-dotnet@v1
      #   with:
      #     dotnet-version: 7.0.101
      - name: Restore packages
        run: dotnet restore
      - name: Build
        run: dotnet build ShapeCrawler/ShapeCrawler.csproj --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal -f net7.0
      - name: Create package
        run: dotnet pack --configuration Release
      # - name: Push package
      #   run: |
      #     dotnet nuget push -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json "ShapeCrawler\bin\Release\*.nupkg"