name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  
  test:
    name: Test on framework ${{ matrix.framework_version }}
    runs-on: windows-latest
    strategy:
      matrix:
        framework_version: [ 'net472', 'net48', 'net9.0' ]
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: dotnet test ShapeCrawler.sln -c Release -f ${{ matrix.framework_version }}

  publish:
    needs: test
    name: Publish
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create package
        run: dotnet pack ./src/ShapeCrawler.csproj --configuration Release /p:Version=${{ vars.VERSION }}
      - name: Publish package
        run: dotnet nuget push -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json "src\bin\Release\*.nupkg"