name: Test

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test on .NET 9.0
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4      
      
      - name: Test
        run: dotnet test -c Release -f net9.0